site_name: 'Song Tags for Suno AI'
copyright: by develephant (not affiliated with suno.ai)
nav:
  - 'Song Tags':
    - song-tags/index.md
    - 'Intro': song-tags/intro.md
    - 'Verse': song-tags/verse.md
    - 'Pre-Chrous': song-tags/pre-chrous.md
    - 'Chrous': song-tags/chrous.md
    - 'Hook': song-tags/hook.md
    - 'Break': song-tags/break.md
    - 'Build': song-tags/build.md
    - 'Interlude': song-tags/interlude.md
    - 'Refrain': song-tags/refrain.md
    - 'Outro': song-tags/outro.md
    - 'Fade Out': song-tags/fade-out.md
    - 'End': song-tags/end.md
    - 'Special Tags': song-tags/special-tags.md
  - 'Song Templates': pages/template.md
theme: 
  name: material
  palette:
    scheme: slate
    primary: black
    accent: indigo
  favicon: './imgs/rnd-tiny.png'
  icon:
    logo: 'material/tag-heart'
    menu: material/music-circle
    admonition:
      note: octicons/beaker-16
      abstract: octicons/mark-github-16
      info: octicons/info-16
      tip: octicons/squirrel-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/cpu-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16
  features:
    - navigation.path
    - navigation.prune
    - navigation.indexes
    - header.autohide
    - content.code.copy
  # - navigation.tabs
  # - navigation.sections
  # - content.tabs.link
extra:
  generator: false
  social:
    - icon: material/music-box
      link: https://suno.ai
    - icon: material/github
      link: https://github.com/develephant/suno-songtags
    - icon: material/youtube 
      link: https://youtube.com
    - icon: material/soundcloud
      link: https://soundcloud.com
markdown_extensions:
  - toc:
      toc_depth: 3
  - admonition
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  # - pymdownx.inlinehilite
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
# - def_list
# - pymdownx.details
docs_dir: './docs'
site_dir: './build'
extra_css:
  - stylesheets/extra.css